-- Task 7:
-- Lucky Shrub need to find out how much revenue their top selling product generated. 
-- Create a stored procedure called GetProfit that returns the overall profits generated by a specific product in a specific year. This should be based on the user input of the ProductID and Year. 
-- For example, the output result of GetProfit procedure with the P1 ProductID and Year 2020 is displayed in the screenshot below:

delimiter // 
create procedure GetProfit(product_id varchar(10), inputYear int )
begin 
	declare total_Quantity_Of_Specified_Item int ; 
    declare profit_Of_One_Item decimal(5,2); 
	select sum(Quantity) into total_Quantity_of_Specified_Item from orders where productId= product_id and year(date) = inputYear ; 
    select (sellPrice - BuyPrice) into profit_Of_One_item from products where ProductID= product_id ; 
    select total_Quantity_Of_Specified_Item * profit_Of_One_Item as Profit ; 
end //
delimiter ; 

CALL GetProfit('P1', 2020);
CALL GetProfit('P3', 2022);
Drop procedure GetProfit; 

-- =======================================================================================================================
-- another solution 
-- =======================================================================================================================
delimiter // 
create procedure GetProfit_02 ( product_id varchar (10), inputYear int )
begin 
	set @totalQuantity = (select sum(quantity) from orders where productId = product_id and year(date) = inputYear); 
    set @itemProfit = (select sellPrice - buyPrice from products where productID = product_id );
    select round(@totalQuantity  * @itemProfit  ,2)as Profit_02 ; 
end //
delimiter ; 

call GetProfit_02 ('P1', 2020); 
drop procedure GetProfit_02 ; 


